name = "shell"

[light]
primary = "#2b638b"
on_primary = "#ffffff"
primary_container = "#cce5ff"
on_primary_container = "#001e31"
inverse_primary = "#98ccf9"
primary_fixed = "#cce5ff"
primary_fixed_dim = "#98ccf9"
on_primary_fixed = "#001e31"
on_primary_fixed_variant = "#064b72"
secondary = "#51606f"
on_secondary = "#ffffff"
secondary_container = "#d4e4f6"
on_secondary_container = "#0d1d2a"
secondary_fixed = "#d4e4f6"
secondary_fixed_dim = "#b8c8da"
on_secondary_fixed = "#0d1d2a"
on_secondary_fixed_variant = "#394857"
tertiary = "#66587a"
on_tertiary = "#ffffff"
tertiary_container = "#eddcff"
on_tertiary_container = "#221534"
tertiary_fixed = "#eddcff"
tertiary_fixed_dim = "#d1bfe7"
on_tertiary_fixed = "#221534"
on_tertiary_fixed_variant = "#4e4162"
source_color = "#2c8dcc"
error = "#ba1a1a"
on_error = "#ffffff"
error_container = "#ffdad6"
on_error_container = "#410002"
surface_dim = "#d7dadf"
surface = "#f7f9ff"
surface_bright = "#f7f9ff"
surface_container_lowest = "#ffffff"
surface_container_low = "#f1f4f9"
surface_container = "#ebeef3"
surface_container_high = "#e6e8ee"
surface_container_highest = "#e0e2e8"
on_surface = "#181c20"
on_surface_variant = "#42474e"
outline = "#72787e"
outline_variant = "#c2c7ce"
inverse_surface = "#2d3135"
inverse_on_surface = "#eef1f6"
surface_variant = "#dee3eb"
background = "#f7f9ff"
on_background = "#181c20"
shadow = "#000000"
scrim = "#000000"

[dark]
primary = "#2b638b"
on_primary = "#ffffff"
primary_container = "#cce5ff"
on_primary_container = "#001e31"
inverse_primary = "#98ccf9"
primary_fixed = "#cce5ff"
primary_fixed_dim = "#98ccf9"
on_primary_fixed = "#001e31"
on_primary_fixed_variant = "#064b72"
secondary = "#51606f"
on_secondary = "#ffffff"
secondary_container = "#d4e4f6"
on_secondary_container = "#0d1d2a"
secondary_fixed = "#d4e4f6"
secondary_fixed_dim = "#b8c8da"
on_secondary_fixed = "#0d1d2a"
on_secondary_fixed_variant = "#394857"
tertiary = "#66587a"
on_tertiary = "#ffffff"
tertiary_container = "#eddcff"
on_tertiary_container = "#221534"
tertiary_fixed = "#eddcff"
tertiary_fixed_dim = "#d1bfe7"
on_tertiary_fixed = "#221534"
on_tertiary_fixed_variant = "#4e4162"
source_color = "#2c8dcc"
error = "#ba1a1a"
on_error = "#ffffff"
error_container = "#ffdad6"
on_error_container = "#410002"
surface_dim = "#d7dadf"
surface = "#f7f9ff"
surface_bright = "#f7f9ff"
surface_container_lowest = "#ffffff"
surface_container_low = "#f1f4f9"
surface_container = "#ebeef3"
surface_container_high = "#e6e8ee"
surface_container_highest = "#e0e2e8"
on_surface = "#181c20"
on_surface_variant = "#42474e"
outline = "#72787e"
outline_variant = "#c2c7ce"
inverse_surface = "#2d3135"
inverse_on_surface = "#eef1f6"
surface_variant = "#dee3eb"
background = "#f7f9ff"
on_background = "#181c20"
shadow = "#000000"
scrim = "#000000"
