name = "shell"

[light]
primary = "#814c77"
on_primary = "#ffffff"
primary_container = "#ffd7f3"
on_primary_container = "#340830"
inverse_primary = "#f3b2e4"
primary_fixed = "#ffd7f3"
primary_fixed_dim = "#f3b2e4"
on_primary_fixed = "#340830"
on_primary_fixed_variant = "#67355e"
secondary = "#6e5868"
on_secondary = "#ffffff"
secondary_container = "#f8daee"
on_secondary_container = "#271624"
secondary_fixed = "#f8daee"
secondary_fixed_dim = "#dbbed1"
on_secondary_fixed = "#271624"
on_secondary_fixed_variant = "#554050"
tertiary = "#815343"
on_tertiary = "#ffffff"
tertiary_container = "#ffdbcf"
on_tertiary_container = "#321207"
tertiary_fixed = "#ffdbcf"
tertiary_fixed_dim = "#f5b9a5"
on_tertiary_fixed = "#321207"
on_tertiary_fixed_variant = "#663c2d"
source_color = "#ac94a4"
error = "#ba1a1a"
on_error = "#ffffff"
error_container = "#ffdad6"
on_error_container = "#410002"
surface_dim = "#e3d7dd"
surface = "#fff7f9"
surface_bright = "#fff7f9"
surface_container_lowest = "#ffffff"
surface_container_low = "#fdf0f6"
surface_container = "#f8eaf0"
surface_container_high = "#f2e5eb"
surface_container_highest = "#ecdfe5"
on_surface = "#201a1e"
on_surface_variant = "#4e444b"
outline = "#80747b"
outline_variant = "#d2c2cb"
inverse_surface = "#362e33"
inverse_on_surface = "#faedf3"
surface_variant = "#eedee7"
background = "#fff7f9"
on_background = "#201a1e"
shadow = "#000000"
scrim = "#000000"

[dark]
primary = "#f3b2e4"
on_primary = "#4d1f47"
primary_container = "#67355e"
on_primary_container = "#ffd7f3"
inverse_primary = "#814c77"
primary_fixed = "#ffd7f3"
primary_fixed_dim = "#f3b2e4"
on_primary_fixed = "#340830"
on_primary_fixed_variant = "#67355e"
secondary = "#dbbed1"
on_secondary = "#3e2a39"
secondary_container = "#554050"
on_secondary_container = "#f8daee"
secondary_fixed = "#f8daee"
secondary_fixed_dim = "#dbbed1"
on_secondary_fixed = "#271624"
on_secondary_fixed_variant = "#554050"
tertiary = "#f5b9a5"
on_tertiary = "#4c2619"
tertiary_container = "#663c2d"
on_tertiary_container = "#ffdbcf"
tertiary_fixed = "#ffdbcf"
tertiary_fixed_dim = "#f5b9a5"
on_tertiary_fixed = "#321207"
on_tertiary_fixed_variant = "#663c2d"
source_color = "#ac94a4"
error = "#ffb4ab"
on_error = "#690005"
error_container = "#93000a"
on_error_container = "#ffdad6"
surface_dim = "#181216"
surface = "#181216"
surface_bright = "#3f373c"
surface_container_lowest = "#120c11"
surface_container_low = "#201a1e"
surface_container = "#241e22"
surface_container_high = "#2f282c"
surface_container_highest = "#3a3337"
on_surface = "#ecdfe5"
on_surface_variant = "#d2c2cb"
outline = "#9a8d95"
outline_variant = "#4e444b"
inverse_surface = "#ecdfe5"
inverse_on_surface = "#362e33"
surface_variant = "#4e444b"
background = "#181216"
on_background = "#ecdfe5"
shadow = "#000000"
scrim = "#000000"
