[package]
name = "gtk_learn"
version = "0.1.0"
edition = "2021"

[dependencies]
epoxy = "0.1.0"
gl = "0.14.0"
gtk4 = "0.9"
gtk4-layer-shell = "0.4"
hyprland = "0.3.13"
niri-ipc = "26.4.0"
notify = "8.2.0"
serde = "1.0.228"
serde_json = "1.0.150"
skia-safe = { version= "0.97.2", features = ["gl", "egl", "wayland"] }
